serenity.project.name=Serenity and Cucumber Demo

# https://serenity-bdd.github.io/docs/reference/serenity-properties#serenitylogging
serenity.logging=QUIET
#
#serenity.requirement.types=domain,subdomain,capability,feature